/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CountryRouteImport } from './routes/$country'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as CountrySignupRouteImport } from './routes/$country.signup'
import { Route as CountrySettingsRouteImport } from './routes/$country.settings'
import { Route as CountrySessionsRouteImport } from './routes/$country.sessions'
import { Route as CountryRevenueRouteImport } from './routes/$country.revenue'
import { Route as CountryPatientsRouteImport } from './routes/$country.patients'
import { Route as CountryOnboardingRouteImport } from './routes/$country.onboarding'
import { Route as CountryLoginRouteImport } from './routes/$country.login'
import { Route as CountryFeedbackRouteImport } from './routes/$country.feedback'
import { Route as CountryDashboardRouteImport } from './routes/$country.dashboard'
import { Route as CountryBrandingRouteImport } from './routes/$country.branding'
import { Route as CountryBillingRouteImport } from './routes/$country.billing'
import { Route as CountryAvailabilityRouteImport } from './routes/$country.availability'
import { Route as CountryPatientsPatientIdRouteImport } from './routes/$country.patients.$patientId'
import { Route as CountryAiSoapNotesRouteImport } from './routes/$country.ai.soap-notes'
import { Route as CountryDashboardPatientsIdRouteImport } from './routes/$country.dashboard.patients.$id'

const CountryRoute = CountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountrySignupRoute = CountrySignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => CountryRoute,
} as any)
const CountrySettingsRoute = CountrySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CountryRoute,
} as any)
const CountrySessionsRoute = CountrySessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => CountryRoute,
} as any)
const CountryRevenueRoute = CountryRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => CountryRoute,
} as any)
const CountryPatientsRoute = CountryPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => CountryRoute,
} as any)
const CountryOnboardingRoute = CountryOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => CountryRoute,
} as any)
const CountryLoginRoute = CountryLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CountryRoute,
} as any)
const CountryFeedbackRoute = CountryFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => CountryRoute,
} as any)
const CountryDashboardRoute = CountryDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CountryRoute,
} as any)
const CountryBrandingRoute = CountryBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => CountryRoute,
} as any)
const CountryBillingRoute = CountryBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => CountryRoute,
} as any)
const CountryAvailabilityRoute = CountryAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => CountryRoute,
} as any)
const CountryPatientsPatientIdRoute =
  CountryPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => CountryPatientsRoute,
  } as any)
const CountryAiSoapNotesRoute = CountryAiSoapNotesRouteImport.update({
  id: '/ai/soap-notes',
  path: '/ai/soap-notes',
  getParentRoute: () => CountryRoute,
} as any)
const CountryDashboardPatientsIdRoute =
  CountryDashboardPatientsIdRouteImport.update({
    id: '/patients/$id',
    path: '/patients/$id',
    getParentRoute: () => CountryDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$country': typeof CountryRouteWithChildren
  '/$country/availability': typeof CountryAvailabilityRoute
  '/$country/billing': typeof CountryBillingRoute
  '/$country/branding': typeof CountryBrandingRoute
  '/$country/dashboard': typeof CountryDashboardRouteWithChildren
  '/$country/feedback': typeof CountryFeedbackRoute
  '/$country/login': typeof CountryLoginRoute
  '/$country/onboarding': typeof CountryOnboardingRoute
  '/$country/patients': typeof CountryPatientsRouteWithChildren
  '/$country/revenue': typeof CountryRevenueRoute
  '/$country/sessions': typeof CountrySessionsRoute
  '/$country/settings': typeof CountrySettingsRoute
  '/$country/signup': typeof CountrySignupRoute
  '/book/$slug': typeof BookSlugRoute
  '/$country/ai/soap-notes': typeof CountryAiSoapNotesRoute
  '/$country/patients/$patientId': typeof CountryPatientsPatientIdRoute
  '/$country/dashboard/patients/$id': typeof CountryDashboardPatientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$country': typeof CountryRouteWithChildren
  '/$country/availability': typeof CountryAvailabilityRoute
  '/$country/billing': typeof CountryBillingRoute
  '/$country/branding': typeof CountryBrandingRoute
  '/$country/dashboard': typeof CountryDashboardRouteWithChildren
  '/$country/feedback': typeof CountryFeedbackRoute
  '/$country/login': typeof CountryLoginRoute
  '/$country/onboarding': typeof CountryOnboardingRoute
  '/$country/patients': typeof CountryPatientsRouteWithChildren
  '/$country/revenue': typeof CountryRevenueRoute
  '/$country/sessions': typeof CountrySessionsRoute
  '/$country/settings': typeof CountrySettingsRoute
  '/$country/signup': typeof CountrySignupRoute
  '/book/$slug': typeof BookSlugRoute
  '/$country/ai/soap-notes': typeof CountryAiSoapNotesRoute
  '/$country/patients/$patientId': typeof CountryPatientsPatientIdRoute
  '/$country/dashboard/patients/$id': typeof CountryDashboardPatientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$country': typeof CountryRouteWithChildren
  '/$country/availability': typeof CountryAvailabilityRoute
  '/$country/billing': typeof CountryBillingRoute
  '/$country/branding': typeof CountryBrandingRoute
  '/$country/dashboard': typeof CountryDashboardRouteWithChildren
  '/$country/feedback': typeof CountryFeedbackRoute
  '/$country/login': typeof CountryLoginRoute
  '/$country/onboarding': typeof CountryOnboardingRoute
  '/$country/patients': typeof CountryPatientsRouteWithChildren
  '/$country/revenue': typeof CountryRevenueRoute
  '/$country/sessions': typeof CountrySessionsRoute
  '/$country/settings': typeof CountrySettingsRoute
  '/$country/signup': typeof CountrySignupRoute
  '/book/$slug': typeof BookSlugRoute
  '/$country/ai/soap-notes': typeof CountryAiSoapNotesRoute
  '/$country/patients/$patientId': typeof CountryPatientsPatientIdRoute
  '/$country/dashboard/patients/$id': typeof CountryDashboardPatientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$country'
    | '/$country/availability'
    | '/$country/billing'
    | '/$country/branding'
    | '/$country/dashboard'
    | '/$country/feedback'
    | '/$country/login'
    | '/$country/onboarding'
    | '/$country/patients'
    | '/$country/revenue'
    | '/$country/sessions'
    | '/$country/settings'
    | '/$country/signup'
    | '/book/$slug'
    | '/$country/ai/soap-notes'
    | '/$country/patients/$patientId'
    | '/$country/dashboard/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$country'
    | '/$country/availability'
    | '/$country/billing'
    | '/$country/branding'
    | '/$country/dashboard'
    | '/$country/feedback'
    | '/$country/login'
    | '/$country/onboarding'
    | '/$country/patients'
    | '/$country/revenue'
    | '/$country/sessions'
    | '/$country/settings'
    | '/$country/signup'
    | '/book/$slug'
    | '/$country/ai/soap-notes'
    | '/$country/patients/$patientId'
    | '/$country/dashboard/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/$country'
    | '/$country/availability'
    | '/$country/billing'
    | '/$country/branding'
    | '/$country/dashboard'
    | '/$country/feedback'
    | '/$country/login'
    | '/$country/onboarding'
    | '/$country/patients'
    | '/$country/revenue'
    | '/$country/sessions'
    | '/$country/settings'
    | '/$country/signup'
    | '/book/$slug'
    | '/$country/ai/soap-notes'
    | '/$country/patients/$patientId'
    | '/$country/dashboard/patients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryRoute: typeof CountryRouteWithChildren
  BookSlugRoute: typeof BookSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$country': {
      id: '/$country'
      path: '/$country'
      fullPath: '/$country'
      preLoaderRoute: typeof CountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/signup': {
      id: '/$country/signup'
      path: '/signup'
      fullPath: '/$country/signup'
      preLoaderRoute: typeof CountrySignupRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/settings': {
      id: '/$country/settings'
      path: '/settings'
      fullPath: '/$country/settings'
      preLoaderRoute: typeof CountrySettingsRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/sessions': {
      id: '/$country/sessions'
      path: '/sessions'
      fullPath: '/$country/sessions'
      preLoaderRoute: typeof CountrySessionsRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/revenue': {
      id: '/$country/revenue'
      path: '/revenue'
      fullPath: '/$country/revenue'
      preLoaderRoute: typeof CountryRevenueRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/patients': {
      id: '/$country/patients'
      path: '/patients'
      fullPath: '/$country/patients'
      preLoaderRoute: typeof CountryPatientsRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/onboarding': {
      id: '/$country/onboarding'
      path: '/onboarding'
      fullPath: '/$country/onboarding'
      preLoaderRoute: typeof CountryOnboardingRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/login': {
      id: '/$country/login'
      path: '/login'
      fullPath: '/$country/login'
      preLoaderRoute: typeof CountryLoginRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/feedback': {
      id: '/$country/feedback'
      path: '/feedback'
      fullPath: '/$country/feedback'
      preLoaderRoute: typeof CountryFeedbackRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/dashboard': {
      id: '/$country/dashboard'
      path: '/dashboard'
      fullPath: '/$country/dashboard'
      preLoaderRoute: typeof CountryDashboardRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/branding': {
      id: '/$country/branding'
      path: '/branding'
      fullPath: '/$country/branding'
      preLoaderRoute: typeof CountryBrandingRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/billing': {
      id: '/$country/billing'
      path: '/billing'
      fullPath: '/$country/billing'
      preLoaderRoute: typeof CountryBillingRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/availability': {
      id: '/$country/availability'
      path: '/availability'
      fullPath: '/$country/availability'
      preLoaderRoute: typeof CountryAvailabilityRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/patients/$patientId': {
      id: '/$country/patients/$patientId'
      path: '/$patientId'
      fullPath: '/$country/patients/$patientId'
      preLoaderRoute: typeof CountryPatientsPatientIdRouteImport
      parentRoute: typeof CountryPatientsRoute
    }
    '/$country/ai/soap-notes': {
      id: '/$country/ai/soap-notes'
      path: '/ai/soap-notes'
      fullPath: '/$country/ai/soap-notes'
      preLoaderRoute: typeof CountryAiSoapNotesRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/dashboard/patients/$id': {
      id: '/$country/dashboard/patients/$id'
      path: '/patients/$id'
      fullPath: '/$country/dashboard/patients/$id'
      preLoaderRoute: typeof CountryDashboardPatientsIdRouteImport
      parentRoute: typeof CountryDashboardRoute
    }
  }
}

interface CountryDashboardRouteChildren {
  CountryDashboardPatientsIdRoute: typeof CountryDashboardPatientsIdRoute
}

const CountryDashboardRouteChildren: CountryDashboardRouteChildren = {
  CountryDashboardPatientsIdRoute: CountryDashboardPatientsIdRoute,
}

const CountryDashboardRouteWithChildren =
  CountryDashboardRoute._addFileChildren(CountryDashboardRouteChildren)

interface CountryPatientsRouteChildren {
  CountryPatientsPatientIdRoute: typeof CountryPatientsPatientIdRoute
}

const CountryPatientsRouteChildren: CountryPatientsRouteChildren = {
  CountryPatientsPatientIdRoute: CountryPatientsPatientIdRoute,
}

const CountryPatientsRouteWithChildren = CountryPatientsRoute._addFileChildren(
  CountryPatientsRouteChildren,
)

interface CountryRouteChildren {
  CountryAvailabilityRoute: typeof CountryAvailabilityRoute
  CountryBillingRoute: typeof CountryBillingRoute
  CountryBrandingRoute: typeof CountryBrandingRoute
  CountryDashboardRoute: typeof CountryDashboardRouteWithChildren
  CountryFeedbackRoute: typeof CountryFeedbackRoute
  CountryLoginRoute: typeof CountryLoginRoute
  CountryOnboardingRoute: typeof CountryOnboardingRoute
  CountryPatientsRoute: typeof CountryPatientsRouteWithChildren
  CountryRevenueRoute: typeof CountryRevenueRoute
  CountrySessionsRoute: typeof CountrySessionsRoute
  CountrySettingsRoute: typeof CountrySettingsRoute
  CountrySignupRoute: typeof CountrySignupRoute
  CountryAiSoapNotesRoute: typeof CountryAiSoapNotesRoute
}

const CountryRouteChildren: CountryRouteChildren = {
  CountryAvailabilityRoute: CountryAvailabilityRoute,
  CountryBillingRoute: CountryBillingRoute,
  CountryBrandingRoute: CountryBrandingRoute,
  CountryDashboardRoute: CountryDashboardRouteWithChildren,
  CountryFeedbackRoute: CountryFeedbackRoute,
  CountryLoginRoute: CountryLoginRoute,
  CountryOnboardingRoute: CountryOnboardingRoute,
  CountryPatientsRoute: CountryPatientsRouteWithChildren,
  CountryRevenueRoute: CountryRevenueRoute,
  CountrySessionsRoute: CountrySessionsRoute,
  CountrySettingsRoute: CountrySettingsRoute,
  CountrySignupRoute: CountrySignupRoute,
  CountryAiSoapNotesRoute: CountryAiSoapNotesRoute,
}

const CountryRouteWithChildren =
  CountryRoute._addFileChildren(CountryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryRoute: CountryRouteWithChildren,
  BookSlugRoute: BookSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
